baseurl = "http://acmecomdocs.netlify.com"
languageCode = "en-us"
title = "Acumatica eCommerce Edition"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"
search = true
enableRobotsTXT = true

[params]
  editURL = "https://github.com/kensiumdocs/acmecomdocs/tree/master/site/content/"
  description = "Documentation for Acumatica eCommerce Edition"
  author = "Abdul Hafeez"
  menu = ["basics", "acumatica-setup-and-configuration","acumatica-magento-attribute-mapping", "syncexec", "help", "contributing"]
  custom_css = ["custom.css"]
  custom_js  = []
